// =====================================================================
// 영어 문법 — 문장의 5형식 · 관계대명사(집중) · 관계부사 · 시제 · 수동태 등
// 예문과 해석은 이 앱에서 새로 작성한 것입니다.
// =====================================================================
export interface GExample { en: string; ko: string; note?: string }
export interface GLesson { id: string; title: string; short: string; summary: string; points: string[]; examples: GExample[]; tip?: string }

export const GRAMMAR: GLesson[] = [
  {
    id: 'g5', title: '문장의 5형식', short: '5형식',
    summary: '영어 문장은 동사 뒤에 무엇이 오느냐에 따라 다섯 가지 틀로 나뉩니다. S=주어, V=동사, C=보어, O=목적어.',
    points: [
      '1형식 S + V : 동사만으로 뜻이 완성됩니다. 뒤의 부사(구)는 꾸밈말입니다.',
      '2형식 S + V + C : 보어가 주어의 상태·정체를 설명합니다. (be, become, seem, look, sound, feel, get, remain…)',
      '3형식 S + V + O : 동사의 대상(목적어)이 하나 있습니다.',
      '4형식 S + V + IO + DO : “~에게(간접목적어) ~을(직접목적어)”. give, send, show, teach, buy, make…',
      '4형식 → 3형식 전환: give/send/show/teach는 to, buy/make/cook은 for, ask는 of를 씁니다.',
      '5형식 S + V + O + OC : 목적격보어가 목적어의 상태·행동을 설명합니다. (make, keep, find, call, want, let, have…)',
    ],
    examples: [
      { en: 'The children laughed.', ko: '아이들이 웃었다.', note: '1형식 · S+V' },
      { en: 'The meeting starts at nine.', ko: '회의는 9시에 시작한다.', note: '1형식 · at nine은 부사구(꾸밈말)' },
      { en: 'She became a special education teacher.', ko: '그녀는 특수교사가 되었다.', note: '2형식 · a special education teacher = 주격보어' },
      { en: 'The plan sounds reasonable.', ko: '그 계획은 합리적으로 들린다.', note: '2형식 · 감각동사 + 형용사 (reasonably ×)' },
      { en: 'We visited three schools yesterday.', ko: '우리는 어제 학교 세 곳을 방문했다.', note: '3형식 · three schools = 목적어' },
      { en: 'The principal gave us a warm welcome.', ko: '교장 선생님은 우리를 따뜻하게 맞아 주셨다.', note: '4형식 · us(IO) + a warm welcome(DO)' },
      { en: 'I will send the report to the office.', ko: '보고서를 사무실로 보내겠습니다.', note: '4형식 → 3형식 전환 · send A to B' },
      { en: 'My mother bought a new bag for me.', ko: '어머니가 나에게 새 가방을 사 주셨다.', note: '3형식 전환 · buy는 for' },
      { en: 'The music made everyone happy.', ko: '그 음악은 모두를 행복하게 만들었다.', note: '5형식 · happy = 목적격보어(형용사)' },
      { en: 'Please keep the door closed.', ko: '문을 닫힌 채로 두세요.', note: '5형식 · closed = 목적격보어(과거분사)' },
      { en: 'The teacher let the students leave early.', ko: '선생님은 학생들이 일찍 가도록 허락했다.', note: '5형식 · 사역동사 let + 목적어 + 동사원형' },
      { en: 'I want you to join our team.', ko: '나는 네가 우리 팀에 합류하길 원해.', note: '5형식 · want + O + to부정사' },
    ],
    tip: '형식을 가를 때는 “동사 뒤의 명사가 주어와 같은 대상인가(보어), 다른 대상인가(목적어)”를 먼저 보세요.',
  },
  {
    id: 'rp1', title: '관계대명사 ① 주격 · 목적격', short: '관계대명사 기본',
    summary: '관계대명사는 “접속사 + 대명사” 역할을 하며, 앞의 명사(선행사)를 뒤에서 설명하는 형용사절을 만듭니다.',
    points: [
      '선행사가 사람 → who(주격) / whom 또는 who(목적격)',
      '선행사가 사물·동물 → which (주격·목적격 모두)',
      'that은 사람·사물 모두 가능 (단, 계속적 용법과 전치사 바로 뒤에는 쓸 수 없음)',
      '주격 관계대명사 뒤에는 동사가 바로 옵니다. 동사의 수는 선행사에 맞춥니다.',
      '목적격 관계대명사는 생략할 수 있습니다. (the book (which) I read)',
      '주격 관계대명사 + be동사도 함께 생략할 수 있습니다. (the girl (who is) sitting there)',
    ],
    examples: [
      { en: 'I met a teacher who works at the special education center.', ko: '나는 특수교육지원센터에서 일하는 선생님을 만났다.', note: '주격 who · 선행사 a teacher' },
      { en: 'The students who were absent will take the test tomorrow.', ko: '결석한 학생들은 내일 시험을 본다.', note: '주격 · 선행사가 복수라서 were' },
      { en: 'This is the bus which goes to Osaka Castle.', ko: '이것이 오사카성으로 가는 버스다.', note: '주격 which · 사물 선행사' },
      { en: 'The woman whom we interviewed was very kind.', ko: '우리가 면담한 여성은 매우 친절했다.', note: '목적격 whom (회화에서는 who나 생략)' },
      { en: 'The book I borrowed from the library is overdue.', ko: '도서관에서 빌린 책의 반납일이 지났다.', note: '목적격 관계대명사 생략 (the book (which/that) I borrowed)' },
      { en: 'Everything that you need is in this box.', ko: '네게 필요한 모든 것은 이 상자 안에 있다.', note: 'that을 주로 쓰는 경우 · everything, all, nothing 등이 선행사' },
      { en: 'He is the first person that finished the course.', ko: '그는 그 과정을 마친 첫 번째 사람이다.', note: '선행사에 서수·최상급·the only가 있으면 that 선호' },
      { en: 'The boy sitting next to me is my nephew.', ko: '내 옆에 앉아 있는 소년은 내 조카다.', note: '주격 관계대명사 + be 생략 (who is sitting)' },
    ],
    tip: '관계대명사절을 괄호로 묶어 보세요. 괄호를 빼도 문장이 완전해야 합니다. The book (I borrowed) is overdue.',
  },
  {
    id: 'rp2', title: '관계대명사 ② whose · what · 전치사', short: '관계대명사 심화',
    summary: '소유를 나타내는 whose, 선행사를 품은 what, 전치사와 함께 쓰는 관계대명사를 익힙니다.',
    points: [
      'whose + 명사 : 선행사의 소유를 나타냅니다. 사람·사물 모두 가능합니다. (= of which)',
      'what = the thing(s) which : 선행사를 포함하므로 앞에 명사가 없습니다. 명사절(주어·목적어·보어)을 만듭니다.',
      '전치사 + which/whom : 전치사를 관계대명사 앞으로 보낼 수 있습니다. 이때 that과 who는 쓸 수 없습니다.',
      '전치사를 뒤에 두면 관계대명사를 생략할 수 있습니다. (the house I live in)',
      'that(관계대명사)과 that(접속사) 구별: 관계대명사 that 뒤는 불완전한 문장, 접속사 that 뒤는 완전한 문장입니다.',
    ],
    examples: [
      { en: 'I know a student whose father is a pilot.', ko: '나는 아버지가 조종사인 학생을 안다.', note: 'whose + 명사 (그의 아버지)' },
      { en: 'We stayed at a hotel whose rooms overlook the river.', ko: '우리는 방에서 강이 내려다보이는 호텔에 묵었다.', note: '사물 선행사에도 whose' },
      { en: 'What she said surprised everyone.', ko: '그녀가 한 말은 모두를 놀라게 했다.', note: 'what절 = 주어 (The thing which she said)' },
      { en: 'This is exactly what I wanted.', ko: '이게 바로 내가 원하던 것이다.', note: 'what절 = 보어' },
      { en: "Don't put off until tomorrow what you can do today.", ko: '오늘 할 수 있는 일을 내일로 미루지 마라.', note: 'what절 = 목적어 (속담)' },
      { en: 'This is the house in which Mozart was born.', ko: '이곳은 모차르트가 태어난 집이다.', note: '전치사 + which (= where)' },
      { en: 'This is the house which Mozart was born in.', ko: '이곳은 모차르트가 태어난 집이다.', note: '전치사를 뒤에 둔 형태 · which 생략 가능' },
      { en: 'The person with whom I spoke was the manager.', ko: '내가 이야기한 사람은 매니저였다.', note: 'with whom (with who ×, with that ×)' },
      { en: 'I think that the plan will work.', ko: '나는 그 계획이 잘될 거라고 생각한다.', note: '접속사 that · 뒤가 완전한 문장' },
      { en: 'The plan that you suggested will work.', ko: '네가 제안한 계획은 잘될 것이다.', note: '관계대명사 that · suggested의 목적어가 빠진 불완전한 문장' },
    ],
    tip: '앞에 명사가 있으면 which/that, 없으면 what. “the thing(s)”을 넣어 말이 되면 what입니다.',
  },
  {
    id: 'rp3', title: '관계대명사 ③ 계속적 용법', short: '계속적 용법',
    summary: '콤마(,) 뒤의 관계대명사는 선행사에 대한 추가 정보를 덧붙입니다. “그리고 그것은/그 사람은 …”으로 해석합니다.',
    points: [
      '제한적 용법: 콤마 없음. 여러 대상 중 “어떤 것인지” 범위를 좁힙니다.',
      '계속적 용법: 콤마 있음. 이미 정해진 대상에 설명을 더합니다. (= and + 대명사)',
      '계속적 용법에는 that을 쓸 수 없고, 관계대명사를 생략할 수도 없습니다.',
      ', which는 앞 문장 전체를 선행사로 받을 수 있습니다.',
      '수량 표현 + of whom/which : some of whom, most of which, both of which…',
    ],
    examples: [
      { en: 'He has two sons who became doctors.', ko: '그에게는 의사가 된 아들이 둘 있다. (다른 아들이 더 있을 수 있음)', note: '제한적 용법' },
      { en: 'He has two sons, who became doctors.', ko: '그에게는 아들이 둘 있는데, 둘 다 의사가 되었다.', note: '계속적 용법 · = and they' },
      { en: 'We visited Osaka Castle, which was built in the 16th century.', ko: '우리는 오사카성을 방문했는데, 그 성은 16세기에 지어졌다.', note: '고유명사 선행사는 보통 계속적 용법' },
      { en: 'She passed the exam, which surprised her teachers.', ko: '그녀는 시험에 합격했고, 그 사실이 선생님들을 놀라게 했다.', note: ', which = 앞 문장 전체' },
      { en: 'I have many colleagues, most of whom live in Gangneung.', ko: '나에게는 동료가 많은데, 그들 대부분은 강릉에 산다.', note: 'most of whom' },
      { en: 'He bought three books, none of which he has read.', ko: '그는 책을 세 권 샀는데, 그중 한 권도 읽지 않았다.', note: 'none of which' },
    ],
    tip: '해석이 어색하면 콤마 자리에 “그리고”를 넣어 보세요.',
  },
  {
    id: 'rad', title: '관계부사 when · where · why · how', short: '관계부사',
    summary: '관계부사는 “전치사 + which”를 대신하며, 시간·장소·이유·방법을 나타내는 선행사를 설명합니다.',
    points: [
      'when = at/on/in which (시간) · where = in/at which (장소) · why = for which (이유) · how = in which (방법)',
      '관계부사 뒤에는 완전한 문장이 옵니다. (관계대명사 뒤는 불완전)',
      'the way와 how는 함께 쓰지 않습니다. the way I solved it / how I solved it',
      '선행사(the time, the place, the reason)는 생략할 수 있습니다.',
    ],
    examples: [
      { en: 'I remember the day when we first met.', ko: '나는 우리가 처음 만난 날을 기억한다.', note: 'when = on which' },
      { en: 'This is the restaurant where we had okonomiyaki.', ko: '여기가 우리가 오코노미야키를 먹은 식당이다.', note: 'where = at which' },
      { en: 'Tell me the reason why you were late.', ko: '늦은 이유를 말해 줘.', note: 'why = for which' },
      { en: 'This is how I learned Japanese.', ko: '이것이 내가 일본어를 배운 방법이다.', note: 'how (the way how ×)' },
      { en: 'Osaka is the city where I want to live someday.', ko: '오사카는 내가 언젠가 살고 싶은 도시다.', note: 'where + 완전한 문장' },
      { en: 'Osaka is the city which I want to visit again.', ko: '오사카는 내가 다시 방문하고 싶은 도시다.', note: '비교: visit의 목적어가 빠짐 → 관계대명사 which' },
    ],
  },
  {
    id: 'tense', title: '완료 시제', short: '완료 시제',
    summary: '완료 시제는 두 시점을 잇습니다. 과거의 일이 기준 시점까지 어떤 영향을 주는지를 나타냅니다.',
    points: [
      '현재완료 have p.p. : 경험(ever, never), 계속(for, since), 완료(just, already, yet), 결과',
      '명백한 과거 시점(yesterday, ago, last year, When…?)과 현재완료는 함께 쓰지 않습니다.',
      '과거완료 had p.p. : 과거의 기준 시점보다 더 앞선 일 (대과거)',
      '현재완료진행 have been -ing : 과거부터 지금까지 계속되는 동작 강조',
    ],
    examples: [
      { en: 'Have you ever been to Japan?', ko: '일본에 가 본 적 있어요?', note: '현재완료 · 경험' },
      { en: 'I have worked here since 2019.', ko: '나는 2019년부터 여기서 일해 왔다.', note: '현재완료 · 계속 (since + 시점)' },
      { en: 'The train has just left.', ko: '기차가 방금 떠났다.', note: '현재완료 · 완료' },
      { en: 'I lost my key yesterday.', ko: '어제 열쇠를 잃어버렸다.', note: 'yesterday → 단순 과거 (have lost ×)' },
      { en: 'When I arrived, the meeting had already started.', ko: '내가 도착했을 때 회의는 이미 시작되어 있었다.', note: '과거완료 · 도착보다 먼저' },
      { en: 'She has been studying Spanish for two years.', ko: '그녀는 2년째 스페인어를 공부하고 있다.', note: '현재완료진행' },
    ],
  },
  {
    id: 'passive', title: '수동태', short: '수동태',
    summary: '주어가 동작을 “받는” 입장일 때 be + p.p.를 씁니다. 행위자는 by ~로 나타내거나 생략합니다.',
    points: [
      '기본형 be + p.p. (+ by 행위자)',
      '시제는 be동사로 나타냅니다: is made / was made / has been made / will be made / is being made',
      '조동사 + be + p.p. : must be submitted, can be seen',
      '4형식 수동태: 간접목적어·직접목적어 모두 주어로 쓸 수 있습니다.',
      'by 이외의 전치사: be interested in, be covered with, be known to/for, be made of/from',
    ],
    examples: [
      { en: 'Osaka Castle was built by Toyotomi Hideyoshi.', ko: '오사카성은 도요토미 히데요시에 의해 지어졌다.', note: '과거 수동태' },
      { en: 'The report must be submitted by Friday.', ko: '보고서는 금요일까지 제출되어야 한다.', note: '조동사 수동태 · 여기서 by는 “~까지”' },
      { en: 'The road is being repaired now.', ko: '그 도로는 지금 보수 중이다.', note: '진행형 수동태' },
      { en: 'We were given a map at the entrance.', ko: '우리는 입구에서 지도를 받았다.', note: '4형식 수동태 (간접목적어가 주어)' },
      { en: 'The mountain is covered with snow.', ko: '그 산은 눈으로 덮여 있다.', note: 'be covered with' },
      { en: 'Osaka is known for its street food.', ko: '오사카는 길거리 음식으로 유명하다.', note: 'be known for (~로 유명하다)' },
    ],
  },
  {
    id: 'inf', title: 'to부정사와 동명사', short: 'to부정사·동명사',
    summary: '동사를 명사처럼 쓰는 두 가지 방법입니다. 동사에 따라 뒤에 올 형태가 정해져 있습니다.',
    points: [
      'to부정사만 목적어로: want, hope, plan, decide, expect, promise, agree, refuse',
      '동명사만 목적어로: enjoy, finish, avoid, mind, give up, keep, practice, consider',
      '둘 다 가능하지만 뜻이 달라지는 동사: remember/forget/stop/try',
      'remember to do(할 일을 기억하다) / remember doing(한 일을 기억하다)',
      'stop doing(하던 것을 멈추다) / stop to do(~하려고 멈추다)',
    ],
    examples: [
      { en: 'I decided to learn Japanese before the trip.', ko: '나는 여행 전에 일본어를 배우기로 결심했다.', note: 'decide + to부정사' },
      { en: 'We enjoyed walking along the river.', ko: '우리는 강을 따라 걷는 것을 즐겼다.', note: 'enjoy + 동명사' },
      { en: 'Remember to bring your passport.', ko: '여권 가져오는 것을 잊지 마세요.', note: 'remember to do (앞으로 할 일)' },
      { en: 'I remember visiting this temple as a child.', ko: '어릴 때 이 절을 방문했던 기억이 난다.', note: 'remember doing (지난 일)' },
      { en: 'He stopped smoking last year.', ko: '그는 작년에 담배를 끊었다.', note: 'stop doing' },
      { en: 'He stopped to take a picture.', ko: '그는 사진을 찍으려고 멈춰 섰다.', note: 'stop to do (목적)' },
    ],
  },
  {
    id: 'part', title: '분사와 분사구문', short: '분사구문',
    summary: '현재분사(-ing)는 능동·진행, 과거분사(p.p.)는 수동·완료의 의미입니다. 분사구문은 부사절을 짧게 줄인 것입니다.',
    points: [
      '감정 동사: 감정을 일으키면 -ing(exciting), 감정을 느끼면 p.p.(excited)',
      '분사구문 만들기: 접속사 생략 → 주어가 같으면 생략 → 동사를 -ing로',
      '수동의 분사구문은 (Being) p.p.로 시작합니다.',
      '앞선 시제는 Having p.p.로 나타냅니다.',
    ],
    examples: [
      { en: 'The movie was exciting, so we were excited.', ko: '영화가 흥미진진해서 우리는 신이 났다.', note: 'exciting(감정 유발) / excited(감정 느낌)' },
      { en: 'Look at the leaves falling from the tree.', ko: '나무에서 떨어지는 잎을 봐.', note: '현재분사 · 능동·진행' },
      { en: 'I bought a used car.', ko: '나는 중고차를 샀다.', note: '과거분사 · 수동 (사용된 차)' },
      { en: 'Walking along the street, I met an old friend.', ko: '길을 걷다가 옛 친구를 만났다.', note: '= While I was walking along the street' },
      { en: 'Written in easy English, the book is good for beginners.', ko: '쉬운 영어로 쓰여 있어서 그 책은 초보자에게 좋다.', note: '수동 분사구문 · (Being) written' },
      { en: 'Having finished the work, she went home.', ko: '일을 끝낸 뒤 그녀는 집에 갔다.', note: '완료 분사구문 · 먼저 일어난 일' },
    ],
  },
  {
    id: 'subj', title: '가정법', short: '가정법',
    summary: '사실과 반대되거나 가능성이 낮은 일을 가정할 때 시제를 한 단계 과거로 당겨 씁니다.',
    points: [
      '가정법 과거 (현재 사실의 반대): If + 주어 + 과거동사, 주어 + would/could + 동사원형',
      'be동사는 주어와 관계없이 were를 쓰는 것이 원칙입니다. (If I were you)',
      '가정법 과거완료 (과거 사실의 반대): If + had p.p., would have p.p.',
      'I wish + 과거(현재 소망) / I wish + had p.p.(과거 후회)',
      'as if + 과거 : 마치 ~인 것처럼',
    ],
    examples: [
      { en: 'If I had more time, I would travel around Japan.', ko: '시간이 더 있다면 일본 일주를 할 텐데.', note: '가정법 과거' },
      { en: 'If I were you, I would buy the Express Pass.', ko: '내가 너라면 익스프레스 패스를 살 거야.', note: 'If I were you' },
      { en: 'If we had left earlier, we would have caught the train.', ko: '더 일찍 출발했더라면 기차를 탔을 텐데.', note: '가정법 과거완료' },
      { en: 'I wish I could speak Japanese fluently.', ko: '일본어를 유창하게 할 수 있으면 좋을 텐데.', note: 'I wish + 과거' },
      { en: 'I wish I had studied harder.', ko: '더 열심히 공부했더라면 좋았을 텐데.', note: 'I wish + 과거완료' },
      { en: 'He talks as if he knew everything.', ko: '그는 마치 모든 것을 아는 것처럼 말한다.', note: 'as if + 과거' },
    ],
  },
  {
    id: 'comp', title: '비교 구문', short: '비교',
    summary: '원급·비교급·최상급과 자주 쓰는 비교 관용 표현입니다.',
    points: [
      'as + 원급 + as : ~만큼 …한 / not as(so) ~ as : ~만큼 …하지 않은',
      '비교급 강조: much, even, far, still, a lot (very ×)',
      'The + 비교급, the + 비교급 : ~할수록 더 …하다',
      '비교급 + and + 비교급 : 점점 더 ~한',
      '최상급 의미: No other ~ is as/so … as / 비교급 + than any other + 단수명사',
    ],
    examples: [
      { en: 'This ramen is as good as the one in Tokyo.', ko: '이 라멘은 도쿄의 라멘만큼 맛있다.', note: 'as ~ as' },
      { en: 'The Rapi:t is much faster than the local train.', ko: '라피트는 완행열차보다 훨씬 빠르다.', note: '비교급 강조 much' },
      { en: 'The earlier you arrive, the shorter you wait.', ko: '일찍 도착할수록 덜 기다린다.', note: 'the 비교급, the 비교급' },
      { en: 'It is getting colder and colder.', ko: '날씨가 점점 추워지고 있다.', note: '비교급 and 비교급' },
      { en: 'Osaka Castle is more famous than any other castle in the city.', ko: '오사카성은 그 도시의 다른 어떤 성보다 유명하다.', note: '비교급 + than any other + 단수명사' },
    ],
  },
  {
    id: 'modal', title: '조동사 + have p.p.', short: '조동사 완료',
    summary: '과거의 일에 대한 추측·후회를 나타냅니다.',
    points: [
      'must have p.p. : ~했음에 틀림없다 (강한 추측)',
      "can't have p.p. : ~했을 리가 없다",
      'may/might have p.p. : ~했을지도 모른다',
      'should have p.p. : ~했어야 했는데 (후회·유감)',
      'could have p.p. : ~할 수도 있었는데',
    ],
    examples: [
      { en: 'She must have missed the bus.', ko: '그녀는 버스를 놓친 게 틀림없다.', note: 'must have p.p.' },
      { en: "He can't have said that.", ko: '그가 그런 말을 했을 리가 없다.', note: "can't have p.p." },
      { en: 'I might have left my umbrella on the train.', ko: '우산을 기차에 두고 내렸을지도 모른다.', note: 'might have p.p.' },
      { en: 'We should have booked the tickets earlier.', ko: '표를 더 일찍 예매했어야 했는데.', note: 'should have p.p. · 후회' },
      { en: 'You could have asked me for help.', ko: '나한테 도움을 청할 수도 있었잖아.', note: 'could have p.p.' },
    ],
  },
  {
    id: 'emph', title: '강조 · 도치 · 간접의문문', short: '강조·도치',
    summary: '문장의 특정 부분을 강조하거나, 의문문을 다른 문장 안에 넣는 방법입니다.',
    points: [
      'It is ~ that 강조구문 : 강조할 말을 It is와 that 사이에 둡니다.',
      '동사 강조: do/does/did + 동사원형',
      '부정어(Never, Little, Hardly, Not only…) 도치: 부정어 + 조동사 + 주어',
      '간접의문문: 의문사 + 주어 + 동사 (평서문 어순). 의문사가 없으면 if/whether',
    ],
    examples: [
      { en: 'It was in Osaka that I first tried takoyaki.', ko: '내가 처음 타코야키를 먹어 본 곳은 바로 오사카였다.', note: 'It is ~ that 강조' },
      { en: 'I do appreciate your help.', ko: '도와주셔서 정말 감사합니다.', note: '동사 강조 do' },
      { en: 'Never have I seen such a long line.', ko: '그렇게 긴 줄은 한 번도 본 적이 없다.', note: '부정어 도치' },
      { en: 'Could you tell me where the station is?', ko: '역이 어디 있는지 알려 주시겠어요?', note: '간접의문문 (where is the station ×)' },
      { en: 'I wonder if the park is open tomorrow.', ko: '공원이 내일 여는지 궁금하다.', note: '의문사 없는 간접의문문 · if/whether' },
    ],
  },
];

export interface GrammarItem { id: string; en: string; ko: string; note: string; lesson: string; lessonId: string }
export const GRAMMAR_ITEMS: GrammarItem[] = GRAMMAR.flatMap(l => l.examples.map((e, i) => ({ id: `${l.id}-${i}`, en: e.en, ko: e.ko, note: e.note || '', lesson: l.short, lessonId: l.id })));
